name: Hyshitest
version: ${project.version}
main: com.doinc.hyshitest.Hyshitest
api-version: 1.16
authors: [ me ]
description: fuck hypixel
commands:
  deebugwand:
    description: Gives you wand
    usage: /givestick
